#!/usr/bin/env sh
set -eu

WORKDIR_PATH="${JETLINKS_AGENT_CONTAINER_WORKDIR:-/workspace/code/jetlinks-agent-runtime-agent-v2}"
DEFAULTS_DIR="${JETLINKS_AGENT_DEFAULTS_DIR:-/opt/jetlinks-agent-runtime-agent-v2-defaults}"
export JETLINKS_AGENT_BUILTIN_ROOT="${JETLINKS_AGENT_BUILTIN_ROOT:-${DEFAULTS_DIR}}"
export JETLINKS_AGENT_UPLOAD_ROOT="${JETLINKS_AGENT_UPLOAD_ROOT:-${JETLINKS_AGENT_USER_ROOT:-${WORKDIR_PATH}}}"
export JETLINKS_AGENT_CONFIG_UPLOAD_DIR="${JETLINKS_AGENT_CONFIG_UPLOAD_DIR:-${JETLINKS_AGENT_UPLOAD_ROOT}/config/upload}"
export JETLINKS_AGENT_PLUGINS_UPLOAD_DIR="${JETLINKS_AGENT_PLUGINS_UPLOAD_DIR:-${JETLINKS_AGENT_UPLOAD_ROOT}/plugins/upload}"
export JETLINKS_AGENT_STATIC_UPLOAD_DIR="${JETLINKS_AGENT_STATIC_UPLOAD_DIR:-${JETLINKS_AGENT_UPLOAD_ROOT}/static/upload}"

mkdir -p \
  "${JETLINKS_AGENT_CONFIG_UPLOAD_DIR}" \
  "${JETLINKS_AGENT_PLUGINS_UPLOAD_DIR}" \
  "${JETLINKS_AGENT_STATIC_UPLOAD_DIR}"

exec "$@"
